### ISSUE TITLE
snapTo() and setState() together doesn't let snapTo() work correctly

### ISSUE THREAD

**Issue by AbhiShrek** [osdnk/react-native-reanimated-bottom-sheet#207]
I needed to change the content & position of bottom sheet, depending on which button user has clicked.
Below is a small test code i wrote to check if that works, but it didn't.

I have to click the button TWICE, in order to snap the bottom sheet to its intended position.

```
import React from 'react'
import { StyleSheet, Text, View, Button } from 'react-native'
import BottomSheet from 'reanimated-bottom-sheet'

export default class Example extends React.Component {
  state = { case : 1 }

  renderInner = () => (
    <View style={styles.panel}>
      { this.state.case == 1 && 
        <Text> Case 1</Text>
      }
      { this.state.case == 2 && 
        <Text> Case 2</Text>
      }      
      { this.state.case == 3 && 
        <Text> Case 3</Text>
      }
    </View>
  )

  bs = React.createRef()

  render() {
    return (
      <View style={styles.container}>
        <BottomSheet
          ref={this.bs}
          snapPoints={[500, 250, 0]}
          renderContent={this.renderInner}
          initialSnap={1}
        />
        <Button onPress={()=> {this.bs.current.snapTo(0); this.setState({case:1});}} title='Button 1' />
        <Button onPress={()=> {this.bs.current.snapTo(1); this.setState({case:2});}} title='Button 2' />
        <Button onPress={()=> {this.bs.current.snapTo(2); this.setState({case:3});}} title='Button 3' />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  panel: {
    height: 600,
    padding: 20,
    backgroundColor: '#f7f5eee8',
  },
})
```

But if i remove the `setState()` call from the Button `onPress()` call, snap is working fine. (single click button to snap it to intended position)

```
        <Button onPress={()=> this.bs.current.snapTo(0)} title='Button 1' />
        <Button onPress={()=> this.bs.current.snapTo(1)} title='Button 2' />
        <Button onPress={()=> this.bs.current.snapTo(2)} title='Button 3' />
```

Environment Info :
react : 16.13.1
react-native : 0.62.2
iOS Simulator - iPhone 11 / iOS 13.3

**Comment by SimonePit** [comment]
Hi, same problem. 
I solved with this code:

markerTapped = (index) => {
    console.log(index);
    this.setState(
      { selectedMarkerIndex: index },
      () => this.bs.current.snapTo(0)
    );
  }

**Comment by VincentQuillien** [comment]
For those using hooks: call `snapTo` inside a useEffect observing the state.

**Comment by LuisRego** [comment]
@AbhiShrek , I'm having the same issue with `this.setState({})`. If I go directly to `snapTo` the bottom sheet opens without any performance issues.

**Comment by karank07** [comment]
Any updates? I'm having the same issue, I tried to follow @SimonePit 's solution but still not working for me.
